### PR TITLE
Import fixes

### PR DESCRIPTION
**Pull request by jburel**
Use IJ log file if insight is run as a plug-in.

To test:
- run `./build.py release-clients` to generate the `insight.ij` jar.
- Drop it and unzip it in the plugins folder of image J.
- Start imageJ.
- open the insight log file `omeroinsight.log`
- Open the OMERO plugin. Connect. 
- Check that nothing is added to  `omeroinsight.log`

### CODE REVIEW

**Comment by ximenesuk** [comment]
I'll look at this later today but is it intended to run with the original `loci_tools.jar`?

**Comment by jburel** [comment]
Good point, I have only handled the logging part. I will have to remove the code detecting if `loci_tools.jar` is present and replace it with ``ome_tools.jar`

**Comment by ximenesuk** [comment]
I have a commit f7bd9cf9 in another branch which copes with a `loci_tools.jar` not supporting our logging by dropping back to a noop logger. I don't know if this is relevant once you have made the fixes in this PR.

**Comment by jburel** [comment]
@ximenesuk: use ome_tools instead of loci_tools done
If the insight is used as an IJ plugin, we will default to the IJ logging.

**Comment by ximenesuk** [comment]
I've tested this to at least check that it needs `ome_tools.jar` rather than `loci_tools.jar` is required and that much is okay.
However with the `ome_tools.jar` as it is I can't login, I assume I need a revised jar, as per B-F PR https://github.com/openmicroscopy/bioformats/pull/882 Can this PR be updated to use the relevant bioformats jar?
/cc @joshmoore @melissalinkert

**Comment by joshmoore** [comment]
@ximenesuk : you should be good to merge this and then change `ome_tools.jar` to `bioformats_nolog.jar` with a `--depends-on` clause to @melissalinkert's PR.

**Comment by ximenesuk** [comment]
I tried building this PR with `container.xml` patched to use `bioformats_nolog.jar` instead of `ome_tools.jar`. Bioformats build okay but when building OMERO I get this:

```
...
tools:
----------=========== bioformats_all ===========----------
...
/Users/cblackburn/Work/repos/ome/components/bioformats/ant/toplevel.xml:930: src '/Users/cblackburn/Work/repos/ome/components/bioformats/artifacts/ome-io.jar' doesn't exist.
```

Is there anything else I need to change?

**Comment by melissalinkert** [comment]
I've just updated openmicroscopy/bioformats#882 - does it work now?

**Comment by ximenesuk** [comment]
Thanks @melissalinkert it builds fine now. I assume the proliferation of jars will be addressed at a docs level.

@jburel the problem I am now having is logging into the server from the plug-in. I can log in using Insight with no problems so the user name and password are valid. This is the first part of the log:

```
Failed to log onto OMERO.
Reason: Cannot log in. User credentials not valid.

Ice.MarshalException
    reason = (null)
    at Ice.ObjectImpl.__read(ObjectImpl.java:255)
    at omero.model.Details.__read(Details.java:495)
    at IceInternal.BasicStream.readObject(BasicStream.java:1590)
    at IceInternal.BasicStream.readPendingObjects(BasicStream.java:1739)
    at omero.api._IAdminDelM.lookupExperimenter(_IAdminDelM.java:1445)
    at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:1895)
    at omero.api.IAdminPrxHelper.lookupExperimenter(IAdminPrxHelper.java:1867)
    at org.openmicroscopy.shoola.env.data.OMEROGateway.login(OMEROGateway.java:1924)
    at org.openmicroscopy.shoola.env.data.DataServicesFactory.connect(DataServicesFactory.java:620)
    at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.attempt(LoginServiceImpl.java:136)
    at org.openmicroscopy.shoola.env.data.login.LoginServiceImpl.login(LoginServiceImpl.java:265)
    at org.openmicroscopy.shoola.env.data.login.LoginManager.login(LoginManager.java:98)
    at org.openmicroscopy.shoola.env.init.SplashScreenInit.onEnd(SplashScreenInit.java:169)
    at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:189)
    at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:486)
    at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:421)
    at org.openmicroscopy.shoola.MainIJPlugin.run(MainIJPlugin.java:247)
    at ij.IJ.runUserPlugIn(IJ.java:195)
    at ij.IJ.runPlugIn(IJ.java:160)
    at ij.Executer.runCommand(Executer.java:128)
    at ij.Executer.run(Executer.java:64)
    at java.lang.Thread.run(Thread.java:695)

OMERO address: localhost
User Name: root -- Password: *****
org.openmicroscopy.shoola.env.data.DSOutOfServiceException: Cannot log in. User credentials not valid.
...
```

On the plus side the logging now looks good with the right bit of Insight's log going to the ImageJ log.

**Comment by jburel** [comment]
@ximenesuk: looks like a mismatch between the version of client and server

**Comment by ximenesuk** [comment]
All the artefacts I am using are from the same local build: server, Insight and plug-ins.

**Comment by jburel** [comment]
@ximenesuk: will checkout your branch later on and test it. I did not have any issue.

**Comment by ximenesuk** [comment]
I'm building from your branch a6b7270 with the following patch:

```
diff --git a/components/insight/config/container.xml b/components/insight/config/container.xml
index 47affe6..1940b64 100644
--- a/components/insight/config/container.xml
+++ b/components/insight/config/container.xml
@@ -352,7 +352,7 @@
     <plugin>
       <id>1</id>
       <!-- The dependencies will be ignored if used as an ImageJ2 or Fiji plugin-->
-      <dependencies>ome_tools.jar</dependencies>
+      <dependencies>bioformats_nolog.jar</dependencies>
       <conjunction>or</conjunction>
       <directory>plugins</directory>
       <info>http://www.openmicroscopy.org/site/products/bio-formats/downloads</info>
```

**Comment by ximenesuk** [comment]
I'm merging @jburel's PR so that this can be tested more widely on Monday in case I have some local problems.

**Pull request merged**
